//! Convert slicer output (layers, perimeters, infill) into G-code.

use glam::DVec2;
use physical_mfg_toolpath::gcode::{GCodeProgram, GCommand};

use crate::config::SlicerConfig;

/// Emit G-code preamble (homing, heating, priming).
pub fn emit_preamble(prog: &mut GCodeProgram, config: &SlicerConfig) {
    prog.comment("Generated by OpenIE CAD Slicer");
    prog.push(GCommand::SetUnitsMetric);
    prog.push(GCommand::AbsoluteMode);
    prog.push(GCommand::HomeAll);

    // Heat bed first (non-blocking), then extruder (blocking)
    prog.push(GCommand::SetBedTemp {
        temp: config.bed_temp,
        wait: false,
    });
    prog.push(GCommand::SetExtruderTemp {
        temp: config.extruder_temp,
        wait: true,
    });
    prog.push(GCommand::SetBedTemp {
        temp: config.bed_temp,
        wait: true,
    });

    // Reset extruder
    prog.push(GCommand::ResetExtruder);
}

/// Emit G-code postamble (cooldown, home, disable steppers).
pub fn emit_postamble(prog: &mut GCodeProgram, _config: &SlicerConfig) {
    prog.push(GCommand::SetFanSpeed { percent: 0.0 });
    prog.push(GCommand::SetExtruderTemp {
        temp: 0.0,
        wait: false,
    });
    prog.push(GCommand::SetBedTemp {
        temp: 0.0,
        wait: false,
    });
    // Retract and lift
    prog.push(GCommand::RelativeMode);
    prog.push(GCommand::RapidMove {
        x: None,
        y: None,
        z: Some(10.0),
    });
    prog.push(GCommand::AbsoluteMode);
    prog.push(GCommand::HomeAll);
    prog.push(GCommand::Raw("M84".into())); // Disable steppers
    prog.push(GCommand::ProgramEnd);
}

/// Emit a layer change: move to Z height, set fan.
pub fn emit_layer_change(
    prog: &mut GCodeProgram,
    z: f64,
    layer_index: usize,
    config: &SlicerConfig,
) {
    prog.comment(format!("Layer {layer_index}, Z={z:.3}"));
    prog.push(GCommand::RapidMove {
        x: None,
        y: None,
        z: Some(z),
    });

    // Fan control
    if layer_index >= config.fan_start_layer {
        prog.push(GCommand::SetFanSpeed {
            percent: config.fan_speed,
        });
    }
}

/// Emit a contour as extrusion moves.
///
/// `e_state` tracks the current E position (absolute extrusion).
/// Returns the updated E position.
pub fn emit_contour(
    prog: &mut GCodeProgram,
    contour_points: &[DVec2],
    z: f64,
    feed: f64,
    e_per_mm: f64,
    e_state: f64,
    travel_speed: f64,
) -> f64 {
    if contour_points.is_empty() {
        return e_state;
    }

    let mut e = e_state;

    // Travel to start point
    prog.push(GCommand::RapidMove {
        x: Some(contour_points[0].x),
        y: Some(contour_points[0].y),
        z: Some(z),
    });

    // Extrude along contour
    let feed_mm_min = feed * 60.0; // Convert mm/s to mm/min
    for i in 1..contour_points.len() {
        let dist = (contour_points[i] - contour_points[i - 1]).length();
        e += dist * e_per_mm;
        prog.push(GCommand::ExtrudeMove {
            x: Some(contour_points[i].x),
            y: Some(contour_points[i].y),
            z: None,
            e,
            f: feed_mm_min,
        });
    }

    // Close the contour: extrude back to start
    if contour_points.len() >= 3 {
        let dist = (*contour_points.last().unwrap() - contour_points[0]).length();
        e += dist * e_per_mm;
        prog.push(GCommand::ExtrudeMove {
            x: Some(contour_points[0].x),
            y: Some(contour_points[0].y),
            z: None,
            e,
            f: feed_mm_min,
        });
    }

    // Small retract for travel
    let _ = travel_speed; // Used in future retraction logic

    e
}

/// Emit infill lines as extrusion moves.
pub fn emit_infill(
    prog: &mut GCodeProgram,
    lines: &[(DVec2, DVec2)],
    z: f64,
    feed: f64,
    e_per_mm: f64,
    e_state: f64,
) -> f64 {
    if lines.is_empty() {
        return e_state;
    }

    let mut e = e_state;
    let feed_mm_min = feed * 60.0;

    for (start, end) in lines {
        // Travel to start
        prog.push(GCommand::RapidMove {
            x: Some(start.x),
            y: Some(start.y),
            z: Some(z),
        });

        // Extrude to end
        let dist = (*end - *start).length();
        e += dist * e_per_mm;
        prog.push(GCommand::ExtrudeMove {
            x: Some(end.x),
            y: Some(end.y),
            z: None,
            e,
            f: feed_mm_min,
        });
    }

    e
}
