//! Emit G-code for laser cutting/engraving.

use glam::DVec2;
use physical_mfg_toolpath::gcode::{GCodeProgram, GCommand};

use crate::config::LaserConfig;

/// Emit laser G-code preamble.
pub fn emit_preamble(prog: &mut GCodeProgram, config: &LaserConfig) {
    prog.comment("Generated by OpenIE CAD Laser CAM");
    prog.push(GCommand::SetUnitsMetric);
    prog.push(GCommand::AbsoluteMode);
    prog.push(GCommand::HomeAll);
    prog.push(GCommand::LaserOff);
    let _ = config;
}

/// Emit laser G-code postamble.
pub fn emit_postamble(prog: &mut GCodeProgram) {
    prog.push(GCommand::LaserOff);
    prog.push(GCommand::RapidMove {
        x: Some(0.0),
        y: Some(0.0),
        z: None,
    });
    prog.push(GCommand::ProgramEnd);
}

/// Emit a single contour as a laser cut path.
pub fn emit_cut_contour(
    prog: &mut GCodeProgram,
    points: &[DVec2],
    config: &LaserConfig,
) {
    if points.is_empty() {
        return;
    }

    // Rapid to start position
    prog.push(GCommand::RapidMove {
        x: Some(points[0].x),
        y: Some(points[0].y),
        z: None,
    });

    // Laser on
    prog.push(GCommand::LaserPower {
        percent: config.cut_power,
    });

    // Cut along contour
    for point in &points[1..] {
        prog.push(GCommand::LinearMove {
            x: Some(point.x),
            y: Some(point.y),
            z: None,
            f: config.cut_speed,
        });
    }

    // Close contour
    if points.len() >= 3 {
        prog.push(GCommand::LinearMove {
            x: Some(points[0].x),
            y: Some(points[0].y),
            z: None,
            f: config.cut_speed,
        });
    }

    // Laser off
    prog.push(GCommand::LaserOff);
}

/// Emit a set of open path segments (from tab-split contours).
pub fn emit_cut_segments(
    prog: &mut GCodeProgram,
    segments: &[Vec<DVec2>],
    config: &LaserConfig,
) {
    for segment in segments {
        if segment.len() < 2 {
            continue;
        }

        // Rapid to start
        prog.push(GCommand::RapidMove {
            x: Some(segment[0].x),
            y: Some(segment[0].y),
            z: None,
        });

        // Laser on
        prog.push(GCommand::LaserPower {
            percent: config.cut_power,
        });

        // Cut along segment
        for point in &segment[1..] {
            prog.push(GCommand::LinearMove {
                x: Some(point.x),
                y: Some(point.y),
                z: None,
                f: config.cut_speed,
            });
        }

        // Laser off
        prog.push(GCommand::LaserOff);
    }
}
