//! `physical-emit-stl` -- Binary and ASCII STL file reader/writer.

use physical_tessellation::{TessMesh, TessVertex};

/// Write a triangle mesh as a binary STL file.
///
/// Returns the raw bytes of a valid binary STL (80-byte header + triangle data).
pub fn write_binary_stl(mesh: &TessMesh) -> Vec<u8> {
    let tri_count = mesh.triangle_count() as u32;
    // Binary STL: 80-byte header + 4-byte triangle count + 50 bytes per triangle
    let mut buf = Vec::with_capacity(84 + 50 * tri_count as usize);

    // 80-byte header (padded with zeros)
    let header = b"binary STL generated by physical-emit-stl";
    buf.extend_from_slice(header);
    buf.extend_from_slice(&vec![0u8; 80 - header.len()]);

    // Triangle count
    buf.extend_from_slice(&tri_count.to_le_bytes());

    // Each triangle: normal (3xf32) + 3 vertices (3xf32 each) + attribute (u16)
    for tri in 0..tri_count as usize {
        let i0 = mesh.indices[tri * 3] as usize;
        let i1 = mesh.indices[tri * 3 + 1] as usize;
        let i2 = mesh.indices[tri * 3 + 2] as usize;

        let v0 = mesh.vertices[i0].position;
        let v1 = mesh.vertices[i1].position;
        let v2 = mesh.vertices[i2].position;

        // Compute face normal from cross product
        let e1 = [v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2]];
        let e2 = [v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2]];
        let nx = e1[1] * e2[2] - e1[2] * e2[1];
        let ny = e1[2] * e2[0] - e1[0] * e2[2];
        let nz = e1[0] * e2[1] - e1[1] * e2[0];
        let len = (nx * nx + ny * ny + nz * nz).sqrt();
        let (nx, ny, nz) = if len > 0.0 {
            (nx / len, ny / len, nz / len)
        } else {
            (0.0, 0.0, 1.0)
        };

        // Normal
        buf.extend_from_slice(&nx.to_le_bytes());
        buf.extend_from_slice(&ny.to_le_bytes());
        buf.extend_from_slice(&nz.to_le_bytes());

        // Vertices
        for v in [v0, v1, v2] {
            buf.extend_from_slice(&v[0].to_le_bytes());
            buf.extend_from_slice(&v[1].to_le_bytes());
            buf.extend_from_slice(&v[2].to_le_bytes());
        }

        // Attribute byte count
        buf.extend_from_slice(&0u16.to_le_bytes());
    }

    buf
}

/// Write a triangle mesh as an ASCII STL string.
///
/// `name` is the solid name used in the STL header.
pub fn write_ascii_stl(mesh: &TessMesh, name: &str) -> String {
    let mut s = String::new();
    s.push_str(&format!("solid {name}\n"));

    for tri in 0..mesh.triangle_count() {
        let i0 = mesh.indices[tri * 3] as usize;
        let i1 = mesh.indices[tri * 3 + 1] as usize;
        let i2 = mesh.indices[tri * 3 + 2] as usize;

        let v0 = mesh.vertices[i0].position;
        let v1 = mesh.vertices[i1].position;
        let v2 = mesh.vertices[i2].position;

        // Compute face normal
        let e1 = [v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2]];
        let e2 = [v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2]];
        let nx = e1[1] * e2[2] - e1[2] * e2[1];
        let ny = e1[2] * e2[0] - e1[0] * e2[2];
        let nz = e1[0] * e2[1] - e1[1] * e2[0];
        let len = (nx * nx + ny * ny + nz * nz).sqrt();
        let (nx, ny, nz) = if len > 0.0 {
            (nx / len, ny / len, nz / len)
        } else {
            (0.0, 0.0, 1.0)
        };

        s.push_str(&format!("  facet normal {nx} {ny} {nz}\n"));
        s.push_str("    outer loop\n");
        s.push_str(&format!("      vertex {} {} {}\n", v0[0], v0[1], v0[2]));
        s.push_str(&format!("      vertex {} {} {}\n", v1[0], v1[1], v1[2]));
        s.push_str(&format!("      vertex {} {} {}\n", v2[0], v2[1], v2[2]));
        s.push_str("    endloop\n");
        s.push_str("  endfacet\n");
    }

    s.push_str(&format!("endsolid {name}\n"));
    s
}

/// Read a binary STL file and return a `TessMesh`.
///
/// Returns `None` if the data is not a valid binary STL.
pub fn read_binary_stl(data: &[u8]) -> Option<TessMesh> {
    if data.len() < 84 {
        return None;
    }

    let tri_count = u32::from_le_bytes([data[80], data[81], data[82], data[83]]) as usize;

    // Validate expected size
    let expected = 84 + tri_count * 50;
    if data.len() < expected {
        return None;
    }

    let mut vertices = Vec::with_capacity(tri_count * 3);
    let mut indices = Vec::with_capacity(tri_count * 3);

    for t in 0..tri_count {
        let base = 84 + t * 50;
        // Skip normal (12 bytes), read 3 vertices (each 12 bytes)
        for v in 0..3u32 {
            let vbase = base + 12 + (v as usize) * 12;
            let x = f32::from_le_bytes([data[vbase], data[vbase + 1], data[vbase + 2], data[vbase + 3]]);
            let y = f32::from_le_bytes([data[vbase + 4], data[vbase + 5], data[vbase + 6], data[vbase + 7]]);
            let z = f32::from_le_bytes([data[vbase + 8], data[vbase + 9], data[vbase + 10], data[vbase + 11]]);

            let idx = vertices.len() as u32;
            vertices.push(TessVertex {
                position: [x, y, z],
                normal: [0.0, 0.0, 1.0],
                uv: [0.0, 0.0],
            });
            indices.push(idx);
        }

        // Recompute normals for each triangle
        let i0 = (t * 3) as usize;
        let p0 = vertices[i0].position;
        let p1 = vertices[i0 + 1].position;
        let p2 = vertices[i0 + 2].position;
        let e1 = [p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2]];
        let e2 = [p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2]];
        let nx = e1[1] * e2[2] - e1[2] * e2[1];
        let ny = e1[2] * e2[0] - e1[0] * e2[2];
        let nz = e1[0] * e2[1] - e1[1] * e2[0];
        let len = (nx * nx + ny * ny + nz * nz).sqrt();
        let n = if len > 0.0 { [nx / len, ny / len, nz / len] } else { [0.0, 0.0, 1.0] };
        for vi in i0..i0 + 3 {
            vertices[vi].normal = n;
        }
    }

    Some(TessMesh { vertices, indices })
}

/// Read an ASCII STL string and return a `TessMesh`.
///
/// Returns `None` if the data is not a valid ASCII STL.
pub fn read_ascii_stl(text: &str) -> Option<TessMesh> {
    if !text.trim_start().starts_with("solid") {
        return None;
    }

    let mut vertices = Vec::new();
    let mut indices = Vec::new();
    let mut current_verts: Vec<[f32; 3]> = Vec::new();

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("vertex") {
            let parts: Vec<&str> = trimmed.split_whitespace().collect();
            if parts.len() < 4 {
                return None;
            }
            let x: f32 = parts[1].parse().ok()?;
            let y: f32 = parts[2].parse().ok()?;
            let z: f32 = parts[3].parse().ok()?;
            current_verts.push([x, y, z]);

            if current_verts.len() == 3 {
                // Compute normal
                let p0 = current_verts[0];
                let p1 = current_verts[1];
                let p2 = current_verts[2];
                let e1 = [p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2]];
                let e2 = [p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2]];
                let nx = e1[1] * e2[2] - e1[2] * e2[1];
                let ny = e1[2] * e2[0] - e1[0] * e2[2];
                let nz = e1[0] * e2[1] - e1[1] * e2[0];
                let len = (nx * nx + ny * ny + nz * nz).sqrt();
                let n = if len > 0.0 { [nx / len, ny / len, nz / len] } else { [0.0, 0.0, 1.0] };

                for v in &current_verts {
                    let idx = vertices.len() as u32;
                    vertices.push(TessVertex {
                        position: *v,
                        normal: n,
                        uv: [0.0, 0.0],
                    });
                    indices.push(idx);
                }
                current_verts.clear();
            }
        }
    }

    if vertices.is_empty() {
        return None;
    }

    Some(TessMesh { vertices, indices })
}

/// Auto-detect STL format (binary or ASCII) and read.
///
/// Returns `None` if the data is not valid STL.
pub fn read_stl(data: &[u8]) -> Option<TessMesh> {
    if data.is_empty() {
        return None;
    }

    // Try ASCII first: check if it starts with "solid"
    if let Ok(text) = std::str::from_utf8(data) {
        if text.trim_start().starts_with("solid") {
            // Could be ASCII — try parsing, but "solid" can also appear in binary header
            if let Some(mesh) = read_ascii_stl(text) {
                if mesh.triangle_count() > 0 {
                    return Some(mesh);
                }
            }
        }
    }

    // Try binary
    read_binary_stl(data)
}
