//! Polymer material property database — thermoplastics, thermosets, elastomers.
//!
//! 105 engineering polymers with full mechanical, thermal, and machinability data.
//! Values sourced from CAMPUS (plastics database), MatWeb, manufacturer TDS,
//! and ASM Handbook Vol 21 (Composites) / Vol 22 (Engineered Materials).
//!
//! Conventions:
//! - `melting_point`: Tg for amorphous polymers, Tm for semi-crystalline
//! - `yield_strength`: tensile yield (0.2% offset or proportional limit)
//! - `hardness`: Shore D scale mapped to HardnessScale::Rockwell (closest available)
//! - `fatigue_endurance`: 20–40% of UTS (polymer-specific ratio)
//! - `machinability_index`: 0–100 relative scale; most unfilled plastics 70–95

use physical_units::*;
use super::{Material, MaterialCategory, HardnessScale};

pub static POLYMERS: &[Material] = &[
    // =========================================================================
    // Thermoplastics
    // =========================================================================

    // --- ABS (Acrylonitrile Butadiene Styrene) ---
    Material {
        id: "ABS-GP",
        name: "ABS (General Purpose)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1050.0),
        yield_strength: Pressure::mpa(40.0),
        ultimate_tensile: Pressure::mpa(44.0),
        elastic_modulus: Pressure::gpa(2.3),
        poissons_ratio: Dimensionless::ratio(0.39),
        thermal_conductivity: ThermalConductivity::w_mk(0.17),
        cte: CTE::um_mk(85.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(105.0), // Tg — amorphous
        hardness: 75.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(13.0),
        machinability_index: 85.0,
        source: "CAMPUS, MatWeb — SABIC Cycolac",
    },
    Material {
        id: "ABS-HI",
        name: "ABS (High Impact)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1060.0),
        yield_strength: Pressure::mpa(34.0),
        ultimate_tensile: Pressure::mpa(38.0),
        elastic_modulus: Pressure::gpa(2.0),
        poissons_ratio: Dimensionless::ratio(0.39),
        thermal_conductivity: ThermalConductivity::w_mk(0.17),
        cte: CTE::um_mk(90.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(100.0), // Tg — amorphous
        hardness: 68.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(11.0),
        machinability_index: 85.0,
        source: "CAMPUS, MatWeb — LG Chem HI-121H",
    },

    // --- PLA ---
    Material {
        id: "PLA",
        name: "PLA (Polylactic Acid)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1240.0),
        yield_strength: Pressure::mpa(60.0),
        ultimate_tensile: Pressure::mpa(65.0),
        elastic_modulus: Pressure::gpa(3.5),
        poissons_ratio: Dimensionless::ratio(0.36),
        thermal_conductivity: ThermalConductivity::w_mk(0.13),
        cte: CTE::um_mk(68.0),
        specific_heat: SpecificHeat::j_kgk(1800.0),
        melting_point: Temperature::celsius(60.0), // Tg — amorphous/semi-cryst blend
        hardness: 83.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(20.0),
        machinability_index: 80.0,
        source: "NatureWorks Ingeo 3D850 TDS, MatWeb",
    },

    // --- PETG ---
    Material {
        id: "PETG",
        name: "PETG (Glycol-modified PET)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1270.0),
        yield_strength: Pressure::mpa(50.0),
        ultimate_tensile: Pressure::mpa(53.0),
        elastic_modulus: Pressure::gpa(2.1),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.18),
        cte: CTE::um_mk(68.0),
        specific_heat: SpecificHeat::j_kgk(1200.0),
        melting_point: Temperature::celsius(81.0), // Tg — amorphous
        hardness: 75.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(16.0),
        machinability_index: 82.0,
        source: "Eastman Spectar TDS, CAMPUS",
    },

    // --- Polyamides (Nylons) ---
    Material {
        id: "PA6",
        name: "PA6 (Nylon 6)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1130.0),
        yield_strength: Pressure::mpa(70.0),
        ultimate_tensile: Pressure::mpa(80.0),
        elastic_modulus: Pressure::gpa(2.8),
        poissons_ratio: Dimensionless::ratio(0.39),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(80.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(220.0), // Tm — semi-crystalline
        hardness: 76.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(24.0),
        machinability_index: 80.0,
        source: "CAMPUS — BASF Ultramid B3S, MatWeb",
    },
    Material {
        id: "PA12",
        name: "PA12 (Nylon 12)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1020.0),
        yield_strength: Pressure::mpa(45.0),
        ultimate_tensile: Pressure::mpa(55.0),
        elastic_modulus: Pressure::gpa(1.4),
        poissons_ratio: Dimensionless::ratio(0.40),
        thermal_conductivity: ThermalConductivity::w_mk(0.23),
        cte: CTE::um_mk(100.0),
        specific_heat: SpecificHeat::j_kgk(1800.0),
        melting_point: Temperature::celsius(178.0), // Tm — semi-crystalline
        hardness: 70.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(17.0),
        machinability_index: 82.0,
        source: "CAMPUS — Evonik Vestamid L1901, MatWeb",
    },
    Material {
        id: "PA66",
        name: "PA66 (Nylon 66)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1140.0),
        yield_strength: Pressure::mpa(80.0),
        ultimate_tensile: Pressure::mpa(85.0),
        elastic_modulus: Pressure::gpa(3.0),
        poissons_ratio: Dimensionless::ratio(0.39),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(80.0),
        specific_heat: SpecificHeat::j_kgk(1670.0),
        melting_point: Temperature::celsius(260.0), // Tm — semi-crystalline
        hardness: 78.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(28.0),
        machinability_index: 78.0,
        source: "CAMPUS — DuPont Zytel 101, MatWeb",
    },
    Material {
        id: "PA66-GF30",
        name: "PA66 GF30 (30% Glass Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1370.0),
        yield_strength: Pressure::mpa(130.0),
        ultimate_tensile: Pressure::mpa(185.0),
        elastic_modulus: Pressure::gpa(9.5),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.33),
        cte: CTE::um_mk(30.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(260.0), // Tm — semi-crystalline
        hardness: 87.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(55.0),
        machinability_index: 55.0,
        source: "CAMPUS — DuPont Zytel 70G30, MatWeb",
    },

    // --- Polycarbonate ---
    Material {
        id: "PC",
        name: "PC (Polycarbonate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1200.0),
        yield_strength: Pressure::mpa(62.0),
        ultimate_tensile: Pressure::mpa(66.0),
        elastic_modulus: Pressure::gpa(2.4),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(67.0),
        specific_heat: SpecificHeat::j_kgk(1200.0),
        melting_point: Temperature::celsius(147.0), // Tg — amorphous
        hardness: 80.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(20.0),
        machinability_index: 85.0,
        source: "CAMPUS — Covestro Makrolon 2805, MatWeb",
    },
    Material {
        id: "PC-ABS",
        name: "PC-ABS Blend",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1120.0),
        yield_strength: Pressure::mpa(50.0),
        ultimate_tensile: Pressure::mpa(55.0),
        elastic_modulus: Pressure::gpa(2.3),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.19),
        cte: CTE::um_mk(73.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(125.0), // Tg — amorphous
        hardness: 76.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(17.0),
        machinability_index: 85.0,
        source: "CAMPUS — SABIC Cycoloy, MatWeb",
    },

    // --- POM (Acetal / Delrin) ---
    Material {
        id: "POM-H",
        name: "POM Homopolymer (Delrin)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1420.0),
        yield_strength: Pressure::mpa(70.0),
        ultimate_tensile: Pressure::mpa(72.0),
        elastic_modulus: Pressure::gpa(3.1),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.31),
        cte: CTE::um_mk(110.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(175.0), // Tm — semi-crystalline
        hardness: 84.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(25.0),
        machinability_index: 90.0,
        source: "DuPont Delrin 500P TDS, MatWeb",
    },
    Material {
        id: "POM-C",
        name: "POM Copolymer",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1410.0),
        yield_strength: Pressure::mpa(65.0),
        ultimate_tensile: Pressure::mpa(68.0),
        elastic_modulus: Pressure::gpa(2.8),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.31),
        cte: CTE::um_mk(110.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(166.0), // Tm — semi-crystalline
        hardness: 81.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(23.0),
        machinability_index: 90.0,
        source: "CAMPUS — Celanese Celcon M90, MatWeb",
    },

    // --- PEEK ---
    Material {
        id: "PEEK",
        name: "PEEK (Polyether Ether Ketone)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1300.0),
        yield_strength: Pressure::mpa(91.0),
        ultimate_tensile: Pressure::mpa(100.0),
        elastic_modulus: Pressure::gpa(3.6),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(47.0),
        specific_heat: SpecificHeat::j_kgk(2180.0),
        melting_point: Temperature::celsius(343.0), // Tm — semi-crystalline
        hardness: 85.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(35.0),
        machinability_index: 60.0,
        source: "Victrex PEEK 450G TDS, MatWeb",
    },
    Material {
        id: "PEEK-GF30",
        name: "PEEK GF30 (30% Glass Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1510.0),
        yield_strength: Pressure::mpa(140.0),
        ultimate_tensile: Pressure::mpa(157.0),
        elastic_modulus: Pressure::gpa(10.0),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.43),
        cte: CTE::um_mk(22.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(343.0), // Tm — semi-crystalline
        hardness: 90.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(50.0),
        machinability_index: 45.0,
        source: "Victrex PEEK 450GL30 TDS, MatWeb",
    },

    // --- PEI (Ultem) ---
    Material {
        id: "PEI-1000",
        name: "PEI (Ultem 1000)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1270.0),
        yield_strength: Pressure::mpa(85.0),
        ultimate_tensile: Pressure::mpa(85.0),
        elastic_modulus: Pressure::gpa(3.0),
        poissons_ratio: Dimensionless::ratio(0.36),
        thermal_conductivity: ThermalConductivity::w_mk(0.22),
        cte: CTE::um_mk(56.0),
        specific_heat: SpecificHeat::j_kgk(2000.0),
        melting_point: Temperature::celsius(217.0), // Tg — amorphous
        hardness: 86.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(28.0),
        machinability_index: 65.0,
        source: "SABIC Ultem 1000 TDS, MatWeb",
    },

    // --- PPS ---
    Material {
        id: "PPS",
        name: "PPS (Polyphenylene Sulfide)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1350.0),
        yield_strength: Pressure::mpa(75.0),
        ultimate_tensile: Pressure::mpa(80.0),
        elastic_modulus: Pressure::gpa(3.8),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.29),
        cte: CTE::um_mk(49.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(280.0), // Tm — semi-crystalline
        hardness: 88.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(26.0),
        machinability_index: 60.0,
        source: "CAMPUS — Celanese Fortron 0205, MatWeb",
    },
    Material {
        id: "PPS-GF40",
        name: "PPS GF40 (40% Glass Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1650.0),
        yield_strength: Pressure::mpa(135.0),
        ultimate_tensile: Pressure::mpa(190.0),
        elastic_modulus: Pressure::gpa(14.0),
        poissons_ratio: Dimensionless::ratio(0.36),
        thermal_conductivity: ThermalConductivity::w_mk(0.40),
        cte: CTE::um_mk(20.0),
        specific_heat: SpecificHeat::j_kgk(900.0),
        melting_point: Temperature::celsius(280.0), // Tm — semi-crystalline
        hardness: 92.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(60.0),
        machinability_index: 45.0,
        source: "CAMPUS — Celanese Fortron 1140L4, MatWeb",
    },

    // --- UHMWPE ---
    Material {
        id: "UHMWPE",
        name: "UHMWPE (Ultra-High MW Polyethylene)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(930.0),
        yield_strength: Pressure::mpa(21.0),
        ultimate_tensile: Pressure::mpa(40.0),
        elastic_modulus: Pressure::gpa(0.69),
        poissons_ratio: Dimensionless::ratio(0.46),
        thermal_conductivity: ThermalConductivity::w_mk(0.42),
        cte: CTE::um_mk(200.0),
        specific_heat: SpecificHeat::j_kgk(1900.0),
        melting_point: Temperature::celsius(136.0), // Tm — semi-crystalline
        hardness: 62.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(12.0),
        machinability_index: 88.0,
        source: "MatWeb — Celanese GUR 4150, Quadrant EPP TDS",
    },

    // --- TPU ---
    Material {
        id: "TPU-85A",
        name: "TPU 85A (Thermoplastic Polyurethane)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1120.0),
        yield_strength: Pressure::mpa(8.0),
        ultimate_tensile: Pressure::mpa(35.0),
        elastic_modulus: Pressure::gpa(0.025),
        poissons_ratio: Dimensionless::ratio(0.48),
        thermal_conductivity: ThermalConductivity::w_mk(0.19),
        cte: CTE::um_mk(150.0),
        specific_heat: SpecificHeat::j_kgk(1800.0),
        melting_point: Temperature::celsius(170.0), // Tm — semi-crystalline soft segment
        hardness: 38.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(10.0),
        machinability_index: 40.0,
        source: "BASF Elastollan 1185A TDS, MatWeb",
    },
    Material {
        id: "TPU-95A",
        name: "TPU 95A (Thermoplastic Polyurethane)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1190.0),
        yield_strength: Pressure::mpa(18.0),
        ultimate_tensile: Pressure::mpa(50.0),
        elastic_modulus: Pressure::gpa(0.060),
        poissons_ratio: Dimensionless::ratio(0.47),
        thermal_conductivity: ThermalConductivity::w_mk(0.22),
        cte: CTE::um_mk(140.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(185.0), // Tm — semi-crystalline soft segment
        hardness: 52.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(15.0),
        machinability_index: 45.0,
        source: "BASF Elastollan 1195A TDS, MatWeb",
    },

    // --- Polyolefins ---
    Material {
        id: "PP",
        name: "PP (Polypropylene Homopolymer)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(905.0),
        yield_strength: Pressure::mpa(35.0),
        ultimate_tensile: Pressure::mpa(38.0),
        elastic_modulus: Pressure::gpa(1.5),
        poissons_ratio: Dimensionless::ratio(0.42),
        thermal_conductivity: ThermalConductivity::w_mk(0.22),
        cte: CTE::um_mk(120.0),
        specific_heat: SpecificHeat::j_kgk(1920.0),
        melting_point: Temperature::celsius(165.0), // Tm — semi-crystalline
        hardness: 68.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(12.0),
        machinability_index: 85.0,
        source: "CAMPUS — LyondellBasell Moplen HP500N, MatWeb",
    },
    Material {
        id: "PE-HD",
        name: "PE-HD (High Density Polyethylene)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(960.0),
        yield_strength: Pressure::mpa(26.0),
        ultimate_tensile: Pressure::mpa(31.0),
        elastic_modulus: Pressure::gpa(1.1),
        poissons_ratio: Dimensionless::ratio(0.42),
        thermal_conductivity: ThermalConductivity::w_mk(0.46),
        cte: CTE::um_mk(130.0),
        specific_heat: SpecificHeat::j_kgk(1900.0),
        melting_point: Temperature::celsius(133.0), // Tm — semi-crystalline
        hardness: 65.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(9.0),
        machinability_index: 88.0,
        source: "CAMPUS — Borealis BorPure, MatWeb",
    },
    Material {
        id: "PE-LD",
        name: "PE-LD (Low Density Polyethylene)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(920.0),
        yield_strength: Pressure::mpa(10.0),
        ultimate_tensile: Pressure::mpa(15.0),
        elastic_modulus: Pressure::gpa(0.20),
        poissons_ratio: Dimensionless::ratio(0.45),
        thermal_conductivity: ThermalConductivity::w_mk(0.33),
        cte: CTE::um_mk(200.0),
        specific_heat: SpecificHeat::j_kgk(2300.0),
        melting_point: Temperature::celsius(110.0), // Tm — semi-crystalline
        hardness: 44.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 75.0,
        source: "MatWeb — DOW LDPE 722, CAMPUS",
    },

    // --- PVC ---
    Material {
        id: "PVC-R",
        name: "PVC Rigid (Unplasticized)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1400.0),
        yield_strength: Pressure::mpa(45.0),
        ultimate_tensile: Pressure::mpa(52.0),
        elastic_modulus: Pressure::gpa(3.0),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.16),
        cte: CTE::um_mk(70.0),
        specific_heat: SpecificHeat::j_kgk(1000.0),
        melting_point: Temperature::celsius(82.0), // Tg — amorphous
        hardness: 80.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(16.0),
        machinability_index: 78.0,
        source: "MatWeb, Vinidex Engineering TDS",
    },

    // --- PMMA ---
    Material {
        id: "PMMA",
        name: "PMMA (Acrylic / Plexiglas)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1190.0),
        yield_strength: Pressure::mpa(72.0),
        ultimate_tensile: Pressure::mpa(75.0),
        elastic_modulus: Pressure::gpa(3.1),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.19),
        cte: CTE::um_mk(70.0),
        specific_heat: SpecificHeat::j_kgk(1470.0),
        melting_point: Temperature::celsius(105.0), // Tg — amorphous
        hardness: 85.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(22.0),
        machinability_index: 88.0,
        source: "CAMPUS — Evonik Plexiglas 8N, MatWeb",
    },

    // =========================================================================
    // Thermosets
    // =========================================================================

    Material {
        id: "EPOXY-UF",
        name: "Epoxy (Unfilled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1200.0),
        yield_strength: Pressure::mpa(60.0),
        ultimate_tensile: Pressure::mpa(72.0),
        elastic_modulus: Pressure::gpa(3.0),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.19),
        cte: CTE::um_mk(55.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(150.0), // Tg — thermoset (fully cured)
        hardness: 86.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(22.0),
        machinability_index: 65.0,
        source: "Huntsman Araldite LY 1564 TDS, MatWeb",
    },
    Material {
        id: "EPOXY-GF",
        name: "Epoxy Glass Fiber Laminate (FR-4 class)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1850.0),
        yield_strength: Pressure::mpa(260.0),
        ultimate_tensile: Pressure::mpa(310.0),
        elastic_modulus: Pressure::gpa(18.0),
        poissons_ratio: Dimensionless::ratio(0.28),
        thermal_conductivity: ThermalConductivity::w_mk(0.35),
        cte: CTE::um_mk(14.0),
        specific_heat: SpecificHeat::j_kgk(1100.0),
        melting_point: Temperature::celsius(170.0), // Tg — thermoset
        hardness: 90.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(100.0),
        machinability_index: 40.0,
        source: "MatWeb — NEMA G-10/FR-4, ASM Handbook Vol 21",
    },
    Material {
        id: "PHENOLIC",
        name: "Phenolic (Bakelite)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1400.0),
        yield_strength: Pressure::mpa(40.0),
        ultimate_tensile: Pressure::mpa(55.0),
        elastic_modulus: Pressure::gpa(7.0),
        poissons_ratio: Dimensionless::ratio(0.30),
        thermal_conductivity: ThermalConductivity::w_mk(0.30),
        cte: CTE::um_mk(35.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(175.0), // decomposition onset; Tg ~170
        hardness: 90.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(18.0),
        machinability_index: 55.0,
        source: "MatWeb — Sumitomo Bakelite, Machinery's Handbook",
    },
    Material {
        id: "UPE",
        name: "Polyester (Unsaturated, Cast)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1200.0),
        yield_strength: Pressure::mpa(40.0),
        ultimate_tensile: Pressure::mpa(55.0),
        elastic_modulus: Pressure::gpa(3.5),
        poissons_ratio: Dimensionless::ratio(0.33),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(60.0),
        specific_heat: SpecificHeat::j_kgk(1200.0),
        melting_point: Temperature::celsius(120.0), // Tg — thermoset (typical general purpose)
        hardness: 82.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(17.0),
        machinability_index: 60.0,
        source: "MatWeb — Reichhold Polylite, ASM Handbook Vol 21",
    },
    Material {
        id: "PUR-R",
        name: "Polyurethane (Rigid Foam, Structural)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1200.0),
        yield_strength: Pressure::mpa(50.0),
        ultimate_tensile: Pressure::mpa(65.0),
        elastic_modulus: Pressure::gpa(2.5),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(100.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(110.0), // Tg — thermoset
        hardness: 78.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(20.0),
        machinability_index: 70.0,
        source: "MatWeb — Huntsman Renshape, CAMPUS",
    },

    // =========================================================================
    // Elastomers
    // =========================================================================

    Material {
        id: "SILICONE-50A",
        name: "Silicone Rubber (Shore 50A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1150.0),
        yield_strength: Pressure::mpa(2.0),
        ultimate_tensile: Pressure::mpa(8.0),
        elastic_modulus: Pressure::gpa(0.005),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.27),
        cte: CTE::um_mk(270.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(-50.0), // Tg — remains flexible to very low temps
        hardness: 18.0, // Shore D equivalent of 50A
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(2.5),
        machinability_index: 20.0,
        source: "Dow Corning Silastic TDS, MatWeb",
    },
    Material {
        id: "NR",
        name: "Natural Rubber (Vulcanized, 60A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(930.0),
        yield_strength: Pressure::mpa(3.0),
        ultimate_tensile: Pressure::mpa(25.0),
        elastic_modulus: Pressure::gpa(0.003),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.15),
        cte: CTE::um_mk(220.0),
        specific_heat: SpecificHeat::j_kgk(1880.0),
        melting_point: Temperature::celsius(-70.0), // Tg — amorphous elastomer
        hardness: 22.0, // Shore D equivalent of ~60A
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(7.0),
        machinability_index: 15.0,
        source: "MatWeb — SMR CV60, Rubber Manufacturers Association",
    },
    Material {
        id: "CR",
        name: "Neoprene (Chloroprene Rubber)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1240.0),
        yield_strength: Pressure::mpa(3.5),
        ultimate_tensile: Pressure::mpa(20.0),
        elastic_modulus: Pressure::gpa(0.007),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.19),
        cte: CTE::um_mk(200.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(-45.0), // Tg — amorphous elastomer
        hardness: 25.0, // Shore D equivalent of ~65A
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(6.0),
        machinability_index: 18.0,
        source: "DuPont Neoprene W TDS, MatWeb",
    },

    // =========================================================================
    // Thermoplastics (additional)
    // =========================================================================

    // --- PP Copolymer ---
    Material {
        id: "PP-COPOL",
        name: "PP Copolymer (Impact Modified)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(900.0),
        yield_strength: Pressure::mpa(25.0),
        ultimate_tensile: Pressure::mpa(30.0),
        elastic_modulus: Pressure::gpa(1.1),
        poissons_ratio: Dimensionless::ratio(0.43),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(140.0),
        specific_heat: SpecificHeat::j_kgk(1950.0),
        melting_point: Temperature::celsius(155.0), // Tm — semi-crystalline (lower than homopolymer)
        hardness: 60.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(9.0),
        machinability_index: 85.0,
        source: "CAMPUS — LyondellBasell Adflex, MatWeb",
    },

    // --- PVC Flexible ---
    Material {
        id: "PVC-F",
        name: "PVC Flexible (Plasticized)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1300.0),
        yield_strength: Pressure::mpa(12.0),
        ultimate_tensile: Pressure::mpa(20.0),
        elastic_modulus: Pressure::gpa(0.010),
        poissons_ratio: Dimensionless::ratio(0.48),
        thermal_conductivity: ThermalConductivity::w_mk(0.14),
        cte: CTE::um_mk(140.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(60.0), // Tg — depressed by plasticizer
        hardness: 15.0, // Shore D equivalent of ~70A
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(6.0),
        machinability_index: 30.0,
        source: "MatWeb — flexible PVC compound, ISO 1163",
    },

    // --- PET ---
    Material {
        id: "PET",
        name: "PET (Polyethylene Terephthalate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1380.0),
        yield_strength: Pressure::mpa(80.0),
        ultimate_tensile: Pressure::mpa(85.0),
        elastic_modulus: Pressure::gpa(3.1),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.24),
        cte: CTE::um_mk(65.0),
        specific_heat: SpecificHeat::j_kgk(1200.0),
        melting_point: Temperature::celsius(255.0), // Tm — semi-crystalline
        hardness: 83.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(28.0),
        machinability_index: 80.0,
        source: "CAMPUS — DuPont Rynite, MatWeb",
    },

    // --- PBT ---
    Material {
        id: "PBT",
        name: "PBT (Polybutylene Terephthalate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1310.0),
        yield_strength: Pressure::mpa(60.0),
        ultimate_tensile: Pressure::mpa(65.0),
        elastic_modulus: Pressure::gpa(2.5),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.29),
        cte: CTE::um_mk(70.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(224.0), // Tm — semi-crystalline
        hardness: 80.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(22.0),
        machinability_index: 78.0,
        source: "CAMPUS — BASF Ultradur B4500, MatWeb",
    },

    // --- PA46 ---
    Material {
        id: "PA46",
        name: "PA46 (Nylon 46, Stanyl)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1180.0),
        yield_strength: Pressure::mpa(100.0),
        ultimate_tensile: Pressure::mpa(100.0),
        elastic_modulus: Pressure::gpa(3.3),
        poissons_ratio: Dimensionless::ratio(0.39),
        thermal_conductivity: ThermalConductivity::w_mk(0.29),
        cte: CTE::um_mk(70.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(295.0), // Tm — semi-crystalline; highest Tm of aliphatic PA
        hardness: 82.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(35.0),
        machinability_index: 72.0,
        source: "DSM Stanyl TW200 TDS, MatWeb",
    },

    // --- PPA ---
    Material {
        id: "PPA",
        name: "PPA (Polyphthalamide)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1180.0),
        yield_strength: Pressure::mpa(100.0),
        ultimate_tensile: Pressure::mpa(110.0),
        elastic_modulus: Pressure::gpa(4.0),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.26),
        cte: CTE::um_mk(50.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(310.0), // Tm — semi-crystalline
        hardness: 84.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(38.0),
        machinability_index: 68.0,
        source: "Solvay Amodel A-1006 TDS, MatWeb",
    },

    // --- PEI Ultem 2300 (30% glass-filled) ---
    Material {
        id: "PEI-2300",
        name: "PEI Ultem 2300 (30% Glass Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1510.0),
        yield_strength: Pressure::mpa(160.0),
        ultimate_tensile: Pressure::mpa(165.0),
        elastic_modulus: Pressure::gpa(9.0),
        poissons_ratio: Dimensionless::ratio(0.36),
        thermal_conductivity: ThermalConductivity::w_mk(0.33),
        cte: CTE::um_mk(23.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(217.0), // Tg — amorphous (same resin as Ultem 1000)
        hardness: 92.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(55.0),
        machinability_index: 45.0,
        source: "SABIC Ultem 2300 TDS, MatWeb",
    },

    // --- PSU ---
    Material {
        id: "PSU",
        name: "PSU (Polysulfone)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1240.0),
        yield_strength: Pressure::mpa(70.0),
        ultimate_tensile: Pressure::mpa(75.0),
        elastic_modulus: Pressure::gpa(2.5),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.26),
        cte: CTE::um_mk(56.0),
        specific_heat: SpecificHeat::j_kgk(1340.0),
        melting_point: Temperature::celsius(185.0), // Tg — amorphous
        hardness: 83.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(25.0),
        machinability_index: 68.0,
        source: "Solvay Udel P-1700 TDS, MatWeb",
    },

    // --- PPSU ---
    Material {
        id: "PPSU",
        name: "PPSU (Polyphenylsulfone)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1290.0),
        yield_strength: Pressure::mpa(70.0),
        ultimate_tensile: Pressure::mpa(75.0),
        elastic_modulus: Pressure::gpa(2.4),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.35),
        cte: CTE::um_mk(55.0),
        specific_heat: SpecificHeat::j_kgk(1250.0),
        melting_point: Temperature::celsius(220.0), // Tg — amorphous; highest Tg of the sulfone family
        hardness: 85.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(25.0),
        machinability_index: 65.0,
        source: "Solvay Radel R-5100 TDS, MatWeb",
    },

    // --- LCP ---
    Material {
        id: "LCP",
        name: "LCP (Liquid Crystal Polymer)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1400.0),
        yield_strength: Pressure::mpa(160.0),
        ultimate_tensile: Pressure::mpa(175.0),
        elastic_modulus: Pressure::gpa(10.0),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.50),
        cte: CTE::um_mk(5.0), // flow direction; very low due to fibrillar morphology
        specific_heat: SpecificHeat::j_kgk(1200.0),
        melting_point: Temperature::celsius(280.0), // Tm — nematic LC transition
        hardness: 90.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(60.0),
        machinability_index: 55.0,
        source: "Celanese Vectra A130 TDS, MatWeb",
    },

    // --- PAI Torlon ---
    Material {
        id: "PAI",
        name: "PAI (Polyamide-imide, Torlon 4203)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1420.0),
        yield_strength: Pressure::mpa(147.0),
        ultimate_tensile: Pressure::mpa(185.0),
        elastic_modulus: Pressure::gpa(4.5),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.26),
        cte: CTE::um_mk(31.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(275.0), // Tg — amorphous; does not melt conventionally
        hardness: 93.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(65.0),
        machinability_index: 50.0,
        source: "Solvay Torlon 4203 TDS, MatWeb",
    },

    // --- PBI ---
    Material {
        id: "PBI",
        name: "PBI (Polybenzimidazole)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1300.0),
        yield_strength: Pressure::mpa(160.0),
        ultimate_tensile: Pressure::mpa(170.0),
        elastic_modulus: Pressure::gpa(5.9),
        poissons_ratio: Dimensionless::ratio(0.36),
        thermal_conductivity: ThermalConductivity::w_mk(0.41),
        cte: CTE::um_mk(23.0),
        specific_heat: SpecificHeat::j_kgk(1100.0),
        melting_point: Temperature::celsius(427.0), // Tg ~420°C — highest Tg of any thermoplastic
        hardness: 94.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(60.0),
        machinability_index: 45.0,
        source: "Solvay Celazole U-60 TDS, MatWeb",
    },

    // =========================================================================
    // Thermosets (additional)
    // =========================================================================

    // --- Epoxy general casting ---
    Material {
        id: "EPOXY-CAST",
        name: "Epoxy (General Casting Resin)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1150.0),
        yield_strength: Pressure::mpa(55.0),
        ultimate_tensile: Pressure::mpa(60.0),
        elastic_modulus: Pressure::gpa(2.8),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.18),
        cte: CTE::um_mk(60.0),
        specific_heat: SpecificHeat::j_kgk(1000.0),
        melting_point: Temperature::celsius(100.0), // Tg — typical ambient-cure system
        hardness: 82.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(18.0),
        machinability_index: 62.0,
        source: "Resoltech 1050/1053 TDS, MatWeb general epoxy casting",
    },

    // --- Vinyl ester ---
    Material {
        id: "VINYL-ESTER",
        name: "Vinyl Ester Resin",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1120.0),
        yield_strength: Pressure::mpa(65.0),
        ultimate_tensile: Pressure::mpa(80.0),
        elastic_modulus: Pressure::gpa(3.5),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.17),
        cte: CTE::um_mk(55.0),
        specific_heat: SpecificHeat::j_kgk(1100.0),
        melting_point: Temperature::celsius(130.0), // Tg — fully cured
        hardness: 84.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(24.0),
        machinability_index: 58.0,
        source: "Ashland Derakane 411-350 TDS, MatWeb",
    },

    // =========================================================================
    // Elastomers (additional)
    // =========================================================================

    // --- EPDM ---
    Material {
        id: "EPDM",
        name: "EPDM Rubber (70A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(870.0),
        yield_strength: Pressure::mpa(3.0),
        ultimate_tensile: Pressure::mpa(15.0),
        elastic_modulus: Pressure::gpa(0.006),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(190.0),
        specific_heat: SpecificHeat::j_kgk(2000.0),
        melting_point: Temperature::celsius(-55.0), // Tg — amorphous elastomer
        hardness: 26.0, // Shore D equivalent of ~70A
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 15.0,
        source: "ExxonMobil Vistalon 7500 TDS, MatWeb",
    },

    // --- NBR ---
    Material {
        id: "NBR",
        name: "NBR Nitrile Rubber (70A, 33% ACN)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1000.0),
        yield_strength: Pressure::mpa(3.5),
        ultimate_tensile: Pressure::mpa(20.0),
        elastic_modulus: Pressure::gpa(0.007),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(175.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(-30.0), // Tg — varies with ACN content
        hardness: 26.0, // Shore D equivalent of ~70A
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(6.0),
        machinability_index: 16.0,
        source: "Lanxess Perbunan NT 3330 TDS, MatWeb",
    },

    // --- FKM (Viton) ---
    Material {
        id: "FKM",
        name: "FKM Fluoroelastomer (Viton, 75A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1800.0),
        yield_strength: Pressure::mpa(7.0),
        ultimate_tensile: Pressure::mpa(20.0),
        elastic_modulus: Pressure::gpa(0.010),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.22),
        cte: CTE::um_mk(160.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(-15.0), // Tg — amorphous; service to 200°C
        hardness: 28.0, // Shore D equivalent of ~75A
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(6.0),
        machinability_index: 12.0,
        source: "Chemours Viton A-500 TDS, MatWeb",
    },

    // =========================================================================
    // Fluoropolymers
    // =========================================================================

    // --- PTFE (Teflon) ---
    Material {
        id: "PTFE",
        name: "PTFE (Polytetrafluoroethylene, Teflon)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(2150.0),
        yield_strength: Pressure::mpa(10.0),
        ultimate_tensile: Pressure::mpa(25.0),
        elastic_modulus: Pressure::gpa(0.50),
        poissons_ratio: Dimensionless::ratio(0.46),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(120.0),
        specific_heat: SpecificHeat::j_kgk(1000.0),
        melting_point: Temperature::celsius(327.0), // Tm — semi-crystalline
        hardness: 55.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(7.0),
        machinability_index: 90.0,
        source: "Chemours Teflon 807N TDS, MatWeb",
    },
    Material {
        id: "PTFE-GF25",
        name: "PTFE 25% Glass Filled",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(2250.0),
        yield_strength: Pressure::mpa(12.0),
        ultimate_tensile: Pressure::mpa(20.0),
        elastic_modulus: Pressure::gpa(1.0),
        poissons_ratio: Dimensionless::ratio(0.42),
        thermal_conductivity: ThermalConductivity::w_mk(0.40),
        cte: CTE::um_mk(80.0),
        specific_heat: SpecificHeat::j_kgk(950.0),
        melting_point: Temperature::celsius(327.0),
        hardness: 60.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(6.0),
        machinability_index: 70.0,
        source: "Chemours Teflon NXT 70 TDS, MatWeb",
    },
    Material {
        id: "PTFE-CF25",
        name: "PTFE 25% Carbon Filled",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(2050.0),
        yield_strength: Pressure::mpa(11.0),
        ultimate_tensile: Pressure::mpa(18.0),
        elastic_modulus: Pressure::gpa(1.4),
        poissons_ratio: Dimensionless::ratio(0.40),
        thermal_conductivity: ThermalConductivity::w_mk(0.70),
        cte: CTE::um_mk(60.0),
        specific_heat: SpecificHeat::j_kgk(950.0),
        melting_point: Temperature::celsius(327.0),
        hardness: 62.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 65.0,
        source: "MatWeb — PTFE carbon-filled compound",
    },

    // --- PVDF ---
    Material {
        id: "PVDF",
        name: "PVDF (Polyvinylidene Fluoride, Kynar)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1780.0),
        yield_strength: Pressure::mpa(45.0),
        ultimate_tensile: Pressure::mpa(50.0),
        elastic_modulus: Pressure::gpa(2.0),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.19),
        cte: CTE::um_mk(130.0),
        specific_heat: SpecificHeat::j_kgk(1380.0),
        melting_point: Temperature::celsius(170.0), // Tm — semi-crystalline
        hardness: 78.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(16.0),
        machinability_index: 82.0,
        source: "Arkema Kynar 740 TDS, MatWeb",
    },

    // --- ETFE ---
    Material {
        id: "ETFE",
        name: "ETFE (Ethylene-Tetrafluoroethylene, Tefzel)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1700.0),
        yield_strength: Pressure::mpa(22.0),
        ultimate_tensile: Pressure::mpa(45.0),
        elastic_modulus: Pressure::gpa(0.80),
        poissons_ratio: Dimensionless::ratio(0.42),
        thermal_conductivity: ThermalConductivity::w_mk(0.24),
        cte: CTE::um_mk(90.0),
        specific_heat: SpecificHeat::j_kgk(1950.0),
        melting_point: Temperature::celsius(267.0), // Tm — semi-crystalline
        hardness: 72.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(14.0),
        machinability_index: 80.0,
        source: "Chemours Tefzel HT2004 TDS, MatWeb",
    },

    // --- FEP ---
    Material {
        id: "FEP",
        name: "FEP (Fluorinated Ethylene Propylene)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(2150.0),
        yield_strength: Pressure::mpa(13.0),
        ultimate_tensile: Pressure::mpa(22.0),
        elastic_modulus: Pressure::gpa(0.48),
        poissons_ratio: Dimensionless::ratio(0.46),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(135.0),
        specific_heat: SpecificHeat::j_kgk(1150.0),
        melting_point: Temperature::celsius(260.0), // Tm — semi-crystalline
        hardness: 56.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(7.0),
        machinability_index: 88.0,
        source: "Chemours Teflon FEP 100 TDS, MatWeb",
    },

    // --- PFA ---
    Material {
        id: "PFA",
        name: "PFA (Perfluoroalkoxy Alkane)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(2150.0),
        yield_strength: Pressure::mpa(12.0),
        ultimate_tensile: Pressure::mpa(28.0),
        elastic_modulus: Pressure::gpa(0.48),
        poissons_ratio: Dimensionless::ratio(0.46),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(120.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(305.0), // Tm — semi-crystalline
        hardness: 58.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(8.0),
        machinability_index: 88.0,
        source: "Chemours Teflon PFA 440HP TDS, MatWeb",
    },

    // --- ECTFE ---
    Material {
        id: "ECTFE",
        name: "ECTFE (Ethylene-Chlorotrifluoroethylene, Halar)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1680.0),
        yield_strength: Pressure::mpa(31.0),
        ultimate_tensile: Pressure::mpa(48.0),
        elastic_modulus: Pressure::gpa(1.7),
        poissons_ratio: Dimensionless::ratio(0.40),
        thermal_conductivity: ThermalConductivity::w_mk(0.16),
        cte: CTE::um_mk(80.0),
        specific_heat: SpecificHeat::j_kgk(1250.0),
        melting_point: Temperature::celsius(242.0), // Tm — semi-crystalline
        hardness: 75.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(14.0),
        machinability_index: 78.0,
        source: "Solvay Halar 300 TDS, MatWeb",
    },

    // =========================================================================
    // Engineering Plastics (additional)
    // =========================================================================

    // --- PPS variants ---
    Material {
        id: "PPS-CF30",
        name: "PPS CF30 (30% Carbon Fiber Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1500.0),
        yield_strength: Pressure::mpa(195.0),
        ultimate_tensile: Pressure::mpa(230.0),
        elastic_modulus: Pressure::gpa(22.0),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(2.0),
        cte: CTE::um_mk(10.0),
        specific_heat: SpecificHeat::j_kgk(900.0),
        melting_point: Temperature::celsius(280.0),
        hardness: 95.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(70.0),
        machinability_index: 40.0,
        source: "Celanese Fortron 6165A6 TDS, MatWeb",
    },
    Material {
        id: "PPS-MF40",
        name: "PPS MF40 (40% Mineral Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1800.0),
        yield_strength: Pressure::mpa(85.0),
        ultimate_tensile: Pressure::mpa(100.0),
        elastic_modulus: Pressure::gpa(10.0),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.55),
        cte: CTE::um_mk(25.0),
        specific_heat: SpecificHeat::j_kgk(850.0),
        melting_point: Temperature::celsius(280.0),
        hardness: 88.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(32.0),
        machinability_index: 48.0,
        source: "Celanese Fortron 4184L6 TDS, MatWeb",
    },

    // --- LCP variants ---
    Material {
        id: "LCP-GF30",
        name: "LCP GF30 (30% Glass Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1610.0),
        yield_strength: Pressure::mpa(135.0),
        ultimate_tensile: Pressure::mpa(155.0),
        elastic_modulus: Pressure::gpa(14.0),
        poissons_ratio: Dimensionless::ratio(0.34),
        thermal_conductivity: ThermalConductivity::w_mk(0.60),
        cte: CTE::um_mk(8.0),
        specific_heat: SpecificHeat::j_kgk(1000.0),
        melting_point: Temperature::celsius(280.0),
        hardness: 92.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(50.0),
        machinability_index: 48.0,
        source: "Celanese Vectra A130 GF30 TDS, MatWeb",
    },
    Material {
        id: "LCP-CF30",
        name: "LCP CF30 (30% Carbon Fiber Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1500.0),
        yield_strength: Pressure::mpa(185.0),
        ultimate_tensile: Pressure::mpa(210.0),
        elastic_modulus: Pressure::gpa(26.0),
        poissons_ratio: Dimensionless::ratio(0.33),
        thermal_conductivity: ThermalConductivity::w_mk(2.5),
        cte: CTE::um_mk(4.0),
        specific_heat: SpecificHeat::j_kgk(1000.0),
        melting_point: Temperature::celsius(280.0),
        hardness: 95.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(65.0),
        machinability_index: 42.0,
        source: "Celanese Vectra C130 TDS, MatWeb",
    },
    Material {
        id: "LCP-HT",
        name: "LCP High-Temperature (Zenite HX)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1400.0),
        yield_strength: Pressure::mpa(140.0),
        ultimate_tensile: Pressure::mpa(165.0),
        elastic_modulus: Pressure::gpa(10.5),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.48),
        cte: CTE::um_mk(4.0),
        specific_heat: SpecificHeat::j_kgk(1100.0),
        melting_point: Temperature::celsius(350.0), // Tm — high-temp LCP grade
        hardness: 91.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(55.0),
        machinability_index: 52.0,
        source: "DuPont Zenite HX6130 TDS, MatWeb",
    },

    // --- Polyimide ---
    Material {
        id: "PI-KAPTON",
        name: "Polyimide (Kapton HN Film)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1420.0),
        yield_strength: Pressure::mpa(69.0),
        ultimate_tensile: Pressure::mpa(231.0),
        elastic_modulus: Pressure::gpa(2.5),
        poissons_ratio: Dimensionless::ratio(0.34),
        thermal_conductivity: ThermalConductivity::w_mk(0.12),
        cte: CTE::um_mk(20.0),
        specific_heat: SpecificHeat::j_kgk(1090.0),
        melting_point: Temperature::celsius(360.0), // Tg — does not melt; decomposes >500 °C
        hardness: 87.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(75.0),
        machinability_index: 55.0,
        source: "DuPont Kapton HN TDS, MatWeb",
    },
    Material {
        id: "PI-VESPEL",
        name: "Polyimide (Vespel SP-1)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1430.0),
        yield_strength: Pressure::mpa(41.0),
        ultimate_tensile: Pressure::mpa(86.0),
        elastic_modulus: Pressure::gpa(3.1),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.35),
        cte: CTE::um_mk(54.0),
        specific_heat: SpecificHeat::j_kgk(1130.0),
        melting_point: Temperature::celsius(388.0), // Tg — amorphous; continuous use to 300 °C
        hardness: 88.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(28.0),
        machinability_index: 50.0,
        source: "DuPont Vespel SP-1 TDS, MatWeb",
    },

    // --- PEEK variants ---
    Material {
        id: "PEEK-CF30",
        name: "PEEK CF30 (30% Carbon Fiber Filled)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1410.0),
        yield_strength: Pressure::mpa(200.0),
        ultimate_tensile: Pressure::mpa(212.0),
        elastic_modulus: Pressure::gpa(17.0),
        poissons_ratio: Dimensionless::ratio(0.36),
        thermal_conductivity: ThermalConductivity::w_mk(2.0),
        cte: CTE::um_mk(15.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(343.0),
        hardness: 92.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(70.0),
        machinability_index: 42.0,
        source: "Victrex PEEK 450CA30 TDS, MatWeb",
    },

    // --- PEKK ---
    Material {
        id: "PEKK",
        name: "PEKK (Polyetherketoneketone)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1300.0),
        yield_strength: Pressure::mpa(110.0),
        ultimate_tensile: Pressure::mpa(115.0),
        elastic_modulus: Pressure::gpa(4.5),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.26),
        cte: CTE::um_mk(40.0),
        specific_heat: SpecificHeat::j_kgk(1200.0),
        melting_point: Temperature::celsius(360.0), // Tm — semi-crystalline
        hardness: 87.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(40.0),
        machinability_index: 58.0,
        source: "Arkema Kepstan 6002 TDS, MatWeb",
    },

    // --- PEK ---
    Material {
        id: "PEK",
        name: "PEK (Polyetherketone)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1310.0),
        yield_strength: Pressure::mpa(110.0),
        ultimate_tensile: Pressure::mpa(120.0),
        elastic_modulus: Pressure::gpa(4.1),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(47.0),
        specific_heat: SpecificHeat::j_kgk(1340.0),
        melting_point: Temperature::celsius(373.0), // Tm — semi-crystalline; higher than PEEK
        hardness: 88.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(42.0),
        machinability_index: 55.0,
        source: "Victrex HT G22 TDS, MatWeb",
    },

    // --- Polystyrene ---
    Material {
        id: "PS-GP",
        name: "PS (General Purpose Polystyrene)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1050.0),
        yield_strength: Pressure::mpa(35.0),
        ultimate_tensile: Pressure::mpa(40.0),
        elastic_modulus: Pressure::gpa(3.0),
        poissons_ratio: Dimensionless::ratio(0.34),
        thermal_conductivity: ThermalConductivity::w_mk(0.14),
        cte: CTE::um_mk(70.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(100.0), // Tg — amorphous
        hardness: 80.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(12.0),
        machinability_index: 82.0,
        source: "CAMPUS — INEOS Styrolution PS 158K, MatWeb",
    },
    Material {
        id: "PS-HI",
        name: "HIPS (High Impact Polystyrene)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1050.0),
        yield_strength: Pressure::mpa(20.0),
        ultimate_tensile: Pressure::mpa(26.0),
        elastic_modulus: Pressure::gpa(2.0),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.14),
        cte: CTE::um_mk(80.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(95.0), // Tg — amorphous
        hardness: 65.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(8.0),
        machinability_index: 85.0,
        source: "CAMPUS — INEOS Styrolution 476I, MatWeb",
    },

    // --- SAN ---
    Material {
        id: "SAN",
        name: "SAN (Styrene Acrylonitrile)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1080.0),
        yield_strength: Pressure::mpa(72.0),
        ultimate_tensile: Pressure::mpa(75.0),
        elastic_modulus: Pressure::gpa(3.6),
        poissons_ratio: Dimensionless::ratio(0.35),
        thermal_conductivity: ThermalConductivity::w_mk(0.17),
        cte: CTE::um_mk(68.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(110.0), // Tg — amorphous
        hardness: 85.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(22.0),
        machinability_index: 80.0,
        source: "CAMPUS — INEOS Styrolution Luran 358N, MatWeb",
    },

    // --- ASA ---
    Material {
        id: "ASA",
        name: "ASA (Acrylonitrile Styrene Acrylate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1070.0),
        yield_strength: Pressure::mpa(42.0),
        ultimate_tensile: Pressure::mpa(48.0),
        elastic_modulus: Pressure::gpa(2.4),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.17),
        cte: CTE::um_mk(85.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(105.0), // Tg — amorphous
        hardness: 76.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(14.0),
        machinability_index: 84.0,
        source: "CAMPUS — INEOS Styrolution Luran S 778T, MatWeb",
    },

    // --- PA6-GF30 ---
    Material {
        id: "PA6-GF30",
        name: "PA6 GF30 (30% Glass Filled Nylon 6)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1360.0),
        yield_strength: Pressure::mpa(120.0),
        ultimate_tensile: Pressure::mpa(165.0),
        elastic_modulus: Pressure::gpa(9.0),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.32),
        cte: CTE::um_mk(30.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(220.0),
        hardness: 86.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(50.0),
        machinability_index: 55.0,
        source: "CAMPUS — BASF Ultramid B3EG6, MatWeb",
    },

    // --- PA610 ---
    Material {
        id: "PA610",
        name: "PA610 (Nylon 610, bio-based)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1080.0),
        yield_strength: Pressure::mpa(55.0),
        ultimate_tensile: Pressure::mpa(60.0),
        elastic_modulus: Pressure::gpa(2.1),
        poissons_ratio: Dimensionless::ratio(0.39),
        thermal_conductivity: ThermalConductivity::w_mk(0.23),
        cte: CTE::um_mk(90.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(215.0), // Tm — semi-crystalline
        hardness: 73.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(18.0),
        machinability_index: 80.0,
        source: "CAMPUS — DuPont Zytel RS LC3060, MatWeb",
    },

    // --- PA11 ---
    Material {
        id: "PA11",
        name: "PA11 (Nylon 11, Rilsan, bio-based)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1040.0),
        yield_strength: Pressure::mpa(40.0),
        ultimate_tensile: Pressure::mpa(55.0),
        elastic_modulus: Pressure::gpa(1.3),
        poissons_ratio: Dimensionless::ratio(0.41),
        thermal_conductivity: ThermalConductivity::w_mk(0.23),
        cte: CTE::um_mk(110.0),
        specific_heat: SpecificHeat::j_kgk(1800.0),
        melting_point: Temperature::celsius(186.0), // Tm — semi-crystalline
        hardness: 68.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(16.0),
        machinability_index: 82.0,
        source: "Arkema Rilsan BESNO TL TDS, MatWeb",
    },

    // --- COC ---
    Material {
        id: "COC",
        name: "COC (Cyclic Olefin Copolymer, Topas)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1020.0),
        yield_strength: Pressure::mpa(63.0),
        ultimate_tensile: Pressure::mpa(63.0),
        elastic_modulus: Pressure::gpa(2.6),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.15),
        cte: CTE::um_mk(60.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(136.0), // Tg — amorphous
        hardness: 82.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(20.0),
        machinability_index: 80.0,
        source: "TOPAS Advanced Polymers 6013 TDS, MatWeb",
    },

    // --- PPE/PPO ---
    Material {
        id: "PPE",
        name: "PPE/PPO (Modified Polyphenylene Ether, Noryl)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1060.0),
        yield_strength: Pressure::mpa(55.0),
        ultimate_tensile: Pressure::mpa(60.0),
        elastic_modulus: Pressure::gpa(2.5),
        poissons_ratio: Dimensionless::ratio(0.37),
        thermal_conductivity: ThermalConductivity::w_mk(0.22),
        cte: CTE::um_mk(60.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(155.0), // Tg — amorphous
        hardness: 80.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(18.0),
        machinability_index: 78.0,
        source: "SABIC Noryl 731 TDS, MatWeb",
    },

    // --- PCT ---
    Material {
        id: "PCT",
        name: "PCT (Polycyclohexylene Dimethylene Terephthalate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1200.0),
        yield_strength: Pressure::mpa(55.0),
        ultimate_tensile: Pressure::mpa(60.0),
        elastic_modulus: Pressure::gpa(2.2),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.23),
        cte: CTE::um_mk(65.0),
        specific_heat: SpecificHeat::j_kgk(1200.0),
        melting_point: Temperature::celsius(285.0), // Tm — semi-crystalline; higher than PET
        hardness: 82.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(18.0),
        machinability_index: 76.0,
        source: "Eastman Thermx PCT TDS, MatWeb",
    },

    // --- PC GF30 ---
    Material {
        id: "PC-GF30",
        name: "PC GF30 (30% Glass Filled Polycarbonate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1430.0),
        yield_strength: Pressure::mpa(110.0),
        ultimate_tensile: Pressure::mpa(125.0),
        elastic_modulus: Pressure::gpa(7.5),
        poissons_ratio: Dimensionless::ratio(0.36),
        thermal_conductivity: ThermalConductivity::w_mk(0.32),
        cte: CTE::um_mk(25.0),
        specific_heat: SpecificHeat::j_kgk(1100.0),
        melting_point: Temperature::celsius(147.0), // Tg — amorphous
        hardness: 88.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(40.0),
        machinability_index: 50.0,
        source: "CAMPUS — Covestro Makrolon 8025 GF30, MatWeb",
    },

    // =========================================================================
    // Bioplastics
    // =========================================================================

    // --- PHA ---
    Material {
        id: "PHA",
        name: "PHA (Polyhydroxyalkanoate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1250.0),
        yield_strength: Pressure::mpa(25.0),
        ultimate_tensile: Pressure::mpa(35.0),
        elastic_modulus: Pressure::gpa(1.5),
        poissons_ratio: Dimensionless::ratio(0.39),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(100.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(170.0), // Tm — semi-crystalline
        hardness: 65.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(10.0),
        machinability_index: 75.0,
        source: "Danimer Scientific Nodax TDS, MatWeb",
    },

    // --- PBS ---
    Material {
        id: "PBS",
        name: "PBS (Polybutylene Succinate, bio-based)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1260.0),
        yield_strength: Pressure::mpa(32.0),
        ultimate_tensile: Pressure::mpa(40.0),
        elastic_modulus: Pressure::gpa(0.70),
        poissons_ratio: Dimensionless::ratio(0.42),
        thermal_conductivity: ThermalConductivity::w_mk(0.22),
        cte: CTE::um_mk(120.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(115.0), // Tm — semi-crystalline
        hardness: 60.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(12.0),
        machinability_index: 78.0,
        source: "Mitsubishi Chemical BioPBS FZ91 TDS, MatWeb",
    },

    // --- TPS ---
    Material {
        id: "TPS",
        name: "TPS (Thermoplastic Starch)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1350.0),
        yield_strength: Pressure::mpa(10.0),
        ultimate_tensile: Pressure::mpa(15.0),
        elastic_modulus: Pressure::gpa(0.30),
        poissons_ratio: Dimensionless::ratio(0.45),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(150.0),
        specific_heat: SpecificHeat::j_kgk(1600.0),
        melting_point: Temperature::celsius(60.0), // processing temperature, degrades >200 °C
        hardness: 40.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 70.0,
        source: "Novamont Mater-Bi TDS, MatWeb",
    },

    // --- PBAT ---
    Material {
        id: "PBAT",
        name: "PBAT (Polybutylene Adipate Terephthalate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1250.0),
        yield_strength: Pressure::mpa(12.0),
        ultimate_tensile: Pressure::mpa(22.0),
        elastic_modulus: Pressure::gpa(0.11),
        poissons_ratio: Dimensionless::ratio(0.45),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(130.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(115.0), // Tm — semi-crystalline
        hardness: 45.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(7.0),
        machinability_index: 72.0,
        source: "BASF ecoflex F Blend TDS, MatWeb",
    },

    // =========================================================================
    // Elastomers (extended)
    // =========================================================================

    // --- Silicone variants ---
    Material {
        id: "SILICONE-70A",
        name: "Silicone Rubber (Shore 70A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1200.0),
        yield_strength: Pressure::mpa(4.0),
        ultimate_tensile: Pressure::mpa(10.0),
        elastic_modulus: Pressure::gpa(0.008),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.30),
        cte: CTE::um_mk(250.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(-45.0), // Tg — remains flexible
        hardness: 25.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(3.0),
        machinability_index: 18.0,
        source: "Dow Corning Silastic 4-4297 TDS, MatWeb",
    },
    Material {
        id: "LSR-50A",
        name: "Liquid Silicone Rubber (LSR, Shore 50A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1130.0),
        yield_strength: Pressure::mpa(2.5),
        ultimate_tensile: Pressure::mpa(9.5),
        elastic_modulus: Pressure::gpa(0.004),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.27),
        cte: CTE::um_mk(280.0),
        specific_heat: SpecificHeat::j_kgk(1050.0),
        melting_point: Temperature::celsius(-55.0), // Tg
        hardness: 18.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(3.0),
        machinability_index: 15.0,
        source: "Wacker Elastosil LR 3003/50 TDS, MatWeb",
    },

    // --- Viton variants ---
    Material {
        id: "FKM-GF",
        name: "FKM Fluoroelastomer (Viton GF, GFLT-600S)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1860.0),
        yield_strength: Pressure::mpa(8.0),
        ultimate_tensile: Pressure::mpa(15.0),
        elastic_modulus: Pressure::gpa(0.012),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(155.0),
        specific_heat: SpecificHeat::j_kgk(1000.0),
        melting_point: Temperature::celsius(-10.0), // Tg — service to 230 °C
        hardness: 30.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 10.0,
        source: "Chemours Viton GF-600S TDS, MatWeb",
    },
    Material {
        id: "FKM-ETP",
        name: "FKM Fluoroelastomer (Viton ETP-600S, perfluoroelastomer-like)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1900.0),
        yield_strength: Pressure::mpa(9.0),
        ultimate_tensile: Pressure::mpa(17.0),
        elastic_modulus: Pressure::gpa(0.014),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.18),
        cte: CTE::um_mk(150.0),
        specific_heat: SpecificHeat::j_kgk(980.0),
        melting_point: Temperature::celsius(-5.0), // Tg — service to 275 °C
        hardness: 32.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 10.0,
        source: "Chemours Viton ETP-600S TDS, MatWeb",
    },

    // --- FFKM (Kalrez) ---
    Material {
        id: "FFKM",
        name: "FFKM Perfluoroelastomer (Kalrez 4079)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(2020.0),
        yield_strength: Pressure::mpa(10.0),
        ultimate_tensile: Pressure::mpa(16.0),
        elastic_modulus: Pressure::gpa(0.011),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(170.0),
        specific_heat: SpecificHeat::j_kgk(900.0),
        melting_point: Temperature::celsius(0.0), // Tg — service to 327 °C
        hardness: 30.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 8.0,
        source: "DuPont Kalrez 4079 TDS, MatWeb",
    },

    // --- HNBR ---
    Material {
        id: "HNBR",
        name: "HNBR (Hydrogenated Nitrile Rubber, 70A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1000.0),
        yield_strength: Pressure::mpa(5.0),
        ultimate_tensile: Pressure::mpa(30.0),
        elastic_modulus: Pressure::gpa(0.008),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.25),
        cte: CTE::um_mk(170.0),
        specific_heat: SpecificHeat::j_kgk(1700.0),
        melting_point: Temperature::celsius(-25.0), // Tg — service to 150 °C
        hardness: 26.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(9.0),
        machinability_index: 16.0,
        source: "Lanxess Therban XT 8889 TDS, MatWeb",
    },

    // --- SBR ---
    Material {
        id: "SBR",
        name: "SBR (Styrene-Butadiene Rubber, 65A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(940.0),
        yield_strength: Pressure::mpa(2.0),
        ultimate_tensile: Pressure::mpa(17.0),
        elastic_modulus: Pressure::gpa(0.004),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(200.0),
        specific_heat: SpecificHeat::j_kgk(1900.0),
        melting_point: Temperature::celsius(-55.0), // Tg — amorphous elastomer
        hardness: 23.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 15.0,
        source: "Goodyear Plioflex 1502 TDS, MatWeb",
    },

    // --- BR ---
    Material {
        id: "BR",
        name: "BR (Polybutadiene Rubber, high-cis)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(910.0),
        yield_strength: Pressure::mpa(2.0),
        ultimate_tensile: Pressure::mpa(15.0),
        elastic_modulus: Pressure::gpa(0.003),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.18),
        cte: CTE::um_mk(210.0),
        specific_heat: SpecificHeat::j_kgk(1900.0),
        melting_point: Temperature::celsius(-100.0), // Tg — very low
        hardness: 20.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 14.0,
        source: "Lanxess Buna CB 24 TDS, MatWeb",
    },

    // --- IIR (Butyl Rubber) ---
    Material {
        id: "IIR",
        name: "IIR (Butyl Rubber, 50A)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(920.0),
        yield_strength: Pressure::mpa(2.0),
        ultimate_tensile: Pressure::mpa(12.0),
        elastic_modulus: Pressure::gpa(0.003),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.13),
        cte: CTE::um_mk(200.0),
        specific_heat: SpecificHeat::j_kgk(1950.0),
        melting_point: Temperature::celsius(-65.0), // Tg — amorphous elastomer
        hardness: 16.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(4.0),
        machinability_index: 14.0,
        source: "ExxonMobil Butyl 268 TDS, MatWeb",
    },

    // --- CSM ---
    Material {
        id: "CSM",
        name: "CSM (Chlorosulfonated Polyethylene, Hypalon)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1250.0),
        yield_strength: Pressure::mpa(4.0),
        ultimate_tensile: Pressure::mpa(18.0),
        elastic_modulus: Pressure::gpa(0.006),
        poissons_ratio: Dimensionless::ratio(0.49),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(190.0),
        specific_heat: SpecificHeat::j_kgk(1400.0),
        melting_point: Temperature::celsius(-25.0), // Tg
        hardness: 24.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(5.0),
        machinability_index: 16.0,
        source: "DuPont Hypalon 40 TDS, MatWeb",
    },

    // =========================================================================
    // Foam Grades
    // =========================================================================

    // --- EPS ---
    Material {
        id: "EPS",
        name: "EPS (Expanded Polystyrene Foam, 30 kg/m3)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(30.0),
        yield_strength: Pressure::mpa(0.18),
        ultimate_tensile: Pressure::mpa(0.35),
        elastic_modulus: Pressure::gpa(0.008),
        poissons_ratio: Dimensionless::ratio(0.10),
        thermal_conductivity: ThermalConductivity::w_mk(0.035),
        cte: CTE::um_mk(70.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(100.0), // softening point
        hardness: 5.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(0.10),
        machinability_index: 90.0,
        source: "BASF Styropor TDS, MatWeb",
    },

    // --- XPS ---
    Material {
        id: "XPS",
        name: "XPS (Extruded Polystyrene Foam, 35 kg/m3)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(35.0),
        yield_strength: Pressure::mpa(0.25),
        ultimate_tensile: Pressure::mpa(0.50),
        elastic_modulus: Pressure::gpa(0.012),
        poissons_ratio: Dimensionless::ratio(0.10),
        thermal_conductivity: ThermalConductivity::w_mk(0.034),
        cte: CTE::um_mk(70.0),
        specific_heat: SpecificHeat::j_kgk(1300.0),
        melting_point: Temperature::celsius(100.0),
        hardness: 6.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(0.12),
        machinability_index: 92.0,
        source: "DOW Styrofoam TDS, MatWeb",
    },

    // --- PUR Rigid Foam (insulation grade) ---
    Material {
        id: "PUR-FOAM",
        name: "PUR Rigid Foam (Insulation, 32 kg/m3)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(32.0),
        yield_strength: Pressure::mpa(0.20),
        ultimate_tensile: Pressure::mpa(0.35),
        elastic_modulus: Pressure::gpa(0.010),
        poissons_ratio: Dimensionless::ratio(0.30),
        thermal_conductivity: ThermalConductivity::w_mk(0.023),
        cte: CTE::um_mk(55.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(110.0), // decomposition onset
        hardness: 5.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(0.08),
        machinability_index: 88.0,
        source: "Huntsman Elastopir TDS, MatWeb",
    },

    // --- EVA Foam ---
    Material {
        id: "EVA-FOAM",
        name: "EVA Foam (Cross-linked, 60 kg/m3)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(60.0),
        yield_strength: Pressure::mpa(0.10),
        ultimate_tensile: Pressure::mpa(0.25),
        elastic_modulus: Pressure::gpa(0.002),
        poissons_ratio: Dimensionless::ratio(0.40),
        thermal_conductivity: ThermalConductivity::w_mk(0.038),
        cte: CTE::um_mk(180.0),
        specific_heat: SpecificHeat::j_kgk(2200.0),
        melting_point: Temperature::celsius(80.0), // softening point
        hardness: 3.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(0.06),
        machinability_index: 85.0,
        source: "Zotefoams Azote TDS, MatWeb",
    },

    // --- PMI Structural Foam (Rohacell) ---
    Material {
        id: "PMI-FOAM",
        name: "PMI Structural Foam (Rohacell 71 IG)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(75.0),
        yield_strength: Pressure::mpa(1.7),
        ultimate_tensile: Pressure::mpa(2.2),
        elastic_modulus: Pressure::gpa(0.092),
        poissons_ratio: Dimensionless::ratio(0.30),
        thermal_conductivity: ThermalConductivity::w_mk(0.031),
        cte: CTE::um_mk(40.0),
        specific_heat: SpecificHeat::j_kgk(1130.0),
        melting_point: Temperature::celsius(180.0), // service limit ~180 °C
        hardness: 10.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(0.60),
        machinability_index: 85.0,
        source: "Evonik Rohacell 71 IG TDS, MatWeb",
    },

    // --- PCTFE ---
    Material {
        id: "PCTFE",
        name: "PCTFE (Polychlorotrifluoroethylene, Kel-F)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(2130.0),
        yield_strength: Pressure::mpa(32.0),
        ultimate_tensile: Pressure::mpa(38.0),
        elastic_modulus: Pressure::gpa(1.3),
        poissons_ratio: Dimensionless::ratio(0.40),
        thermal_conductivity: ThermalConductivity::w_mk(0.14),
        cte: CTE::um_mk(50.0),
        specific_heat: SpecificHeat::j_kgk(900.0),
        melting_point: Temperature::celsius(213.0), // Tm — semi-crystalline
        hardness: 75.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(12.0),
        machinability_index: 82.0,
        source: "3M Kel-F 81 TDS, MatWeb",
    },

    // --- Cellulose Acetate ---
    Material {
        id: "CA",
        name: "CA (Cellulose Acetate)",
        category: MaterialCategory::Polymer,
        density: Density::kg_m3(1280.0),
        yield_strength: Pressure::mpa(30.0),
        ultimate_tensile: Pressure::mpa(40.0),
        elastic_modulus: Pressure::gpa(1.8),
        poissons_ratio: Dimensionless::ratio(0.38),
        thermal_conductivity: ThermalConductivity::w_mk(0.20),
        cte: CTE::um_mk(100.0),
        specific_heat: SpecificHeat::j_kgk(1500.0),
        melting_point: Temperature::celsius(230.0), // Tm — semi-crystalline
        hardness: 65.0,
        hardness_scale: HardnessScale::Rockwell,
        fatigue_endurance: Pressure::mpa(12.0),
        machinability_index: 80.0,
        source: "Eastman Tenite Acetate TDS, MatWeb",
    },
];
